# Preset to match compiled beacon binary
PRESET_BASE: mainnet

# Genesis config
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 4
MIN_GENESIS_TIME: 1606824023  # Use a fixed past timestamp or your own
GENESIS_DELAY: 600

# Forking (optional customization for testnets)
ALTAIR_FORK_EPOCH: 74240
BELLATRIX_FORK_EPOCH: 144896
CAPELLA_FORK_EPOCH: 194048

# Timing
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 32
MIN_SEED_LOOKAHEAD: 1
ETH1_FOLLOW_DISTANCE: 2048

# Deposit Contract
DEPOSIT_CHAIN_ID: 2307
DEPOSIT_NETWORK_ID: 2307
DEPOSIT_CONTRACT_ADDRESS: f39fd6e51aad88f6f4ce6ab8827279cfffab9226

