# Custom network configuration
CONFIG_NAME = "wisdom"
GENESIS_STATE_FILE = "./genesis.ssz"
GENESIS_FORK_VERSION = "0x23070000"
GENESIS_DELAY = 300
SECONDS_PER_SLOT = 12
SECONDS_PER_ETH1_BLOCK = 12
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT = 3
MIN_GENESIS_TIME = 0
CHAIN_ID = 2307
ALTAIR_FORK_EPOCH = 0
BELLATRIX_FORK_EPOCH = 0
CAPELLA_FORK_EPOCH = 0
DENEB_FORK_EPOCH = 0
TERMINAL_TOTAL_DIFFICULTY = 0
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH = 0
MAX_COMMITTEES_PER_SLOT = 64
TARGET_COMMITTEE_SIZE = 128
MAX_VALIDATORS_PER_COMMITTEE = 2048
DEPOSIT_CHAIN_ID = 2307
DEPOSIT_NETWORK_ID = 2307
DEPOSIT_CONTRACT_ADDRESS = "0x0000000000000000000000000000000000000000"
ETH1_FOLLOW_DISTANCE = 1
GRAFFITI = "wisdomacademy.ai"
