# Use mainnet as the base preset for realistic chain behavior
PRESET_BASE: mainnet
CONFIG_NAME: wisdom

# 🕒 Genesis and time config
MIN_GENESIS_TIME: 0
GENESIS_FORK_VERSION: 0x11223344
GENESIS_DELAY: 0

# 🧑‍💻 Validator config for local dev (not mainnet values)
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1
ETH1_FOLLOW_DISTANCE: 1
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 32
INACTIVITY_SCORE_BIAS: 4
INACTIVITY_SCORE_RECOVERY_RATE: 16

# 🔗 Terminal total difficulty to trigger the Merge
TERMINAL_TOTAL_DIFFICULTY: 58750000000000000000000
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 0

# 👷 Withdrawals enabled (Shanghai fork onward)
SHARDING_FORK_EPOCH: 18446744073709551615
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_EPOCH: 0

# 🧪 Optional: Set your own chain ID (matching your genesis.json)
CHAIN_ID: 2307
